language: cpp
sudo: required

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-6
            - cmake
            - cmake-data
            - ninja-build
      env:
        - CXX=g++-6

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
            - george-edison55-precise-backports
          packages:
            - g++-6
            - clang-3.8
            - cmake
            - cmake-data
            - ninja-build
      env:
        - CXX=clang++-3.8

script: |
  mkdir -p build
  cd build
  cmake .. -GNinja\
           -DCMAKE_BUILD_TYPE=Release \
           -DCUTE_RUN_DURING_BUILD=Off \
           -DDABCOMMON_ENABLE_TESTS=On
  cmake --build . --target cute_all
